<?php

$GLOBALS['campos'] = array(
    array(
        
        'id' => 'foto',
        'name' => 'foto_aluno',
        'type' => 'hidden',
        'divisao' => 'Informações Pessoais',
        'object'=> 'aluno',
        'min'=> '',
        'maxlength'=>'',
        'max'=> '',
        'config' => '',
        
    ),
    array(
        'label' => 'Nome do Aluno',
        'id' => 'name',
        'name' => 'aluno',
        'type' => 'text',
        'divisao' => 'Informações Pessoais',
        'size' =>'mb-3 col-md-3',
        'object'=> 'aluno',
        'min'=> '',
        'maxlength'=>'',
        'max'=> '',
        'config' => '',
        'placeholder'=>"Nome completo do aluno",
    ),
    
   array(
        'label' => 'Número do cartão de cidadão ',
        'id' => 'cc',
        'name' => 'cc_aluno',
        'type' => 'number',
        'size' =>'mb-3 col-md-3',
        'divisao' => 'Informações Pessoais',
        'object'=> 'aluno',
        'min'=> '',
        'maxlength'=>'9',
        'max'=> '',
        'config' => '',
        'placeholder'=>"Número do Cartão de Cidadão",
    ),
    array(
        'label' => 'Número de contribuinte (NIF)',
        'id' => 'nif',
        'name' => 'nif_aluno',
        'type' => 'text',
        'size' =>'mb-3 col-md-3',
        'divisao' => 'Informações Pessoais',
        'object'=> 'aluno',
        'min'=> '',
        'maxlength'=>'9',
        'max'=> '',
        'config' => '',
        'placeholder'=>"Número de Contribuinte",
    ),
    array(
        'label' => 'Número de Segurança Social',
        'id' => 'sc',
        'name' => 'sc_aluno',
        'type' => 'number',
        'size' =>'mb-3 col-md-3',
        'divisao' => 'Informações Pessoais',
        'object'=> 'aluno',
        'min'=> '',
        'maxlength'=>'',
        'max'=> '',
        'config' => '',
        'placeholder'=>"Numero da segurança social",
    ),
    array(
        'label' => 'Número de Telefone',
        'id' => 'telefone',
        'name' => 'telefone_aluno',
        'type' => 'number',
        'size' =>'mb-3 col-md-3',
        'divisao' => 'Informações Pessoais',
        'object'=> 'aluno',
        'min'=> '',
        'maxlength'=>'9',
        'max'=> '',
        'config' => '',
        'placeholder'=>"123 456 789",
    ),
    array(
        'label' => 'Email do Aluno',
        'id' => 'email',
        'name' => 'email_aluno',
        'type' => 'email',
        'size' => 'mb-3 col-md-3',
        'divisao' => 'Informações Pessoais',
        'object' => 'aluno',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => '',
        'placeholder'=>"aluno@gmail.com",
    ),
    array(
        'label' => 'Data de Nascimento ',
        'id' => 'date',
        'name' => 'data_nascimento_aluno',
        'type' => 'date',
        'size' =>'mb-3 col-md-3',
        'divisao' => 'Informações Pessoais',
        'object'=> 'aluno',
        'min'=> date('Y-m-d', strtotime('-19 years')),
        'maxlength'=>'',
        'max'=> date('Y-m-d', strtotime('-6 years')),
        'config' => '',
        'placeholder'=>"",
    ),

    array(
        'label' => 'Género',
        'id' => 'genero',
        'name' => 'genero',
        'type' => 'combobox',
        'size' =>'mb-3 col-md-3',
        'divisao' => 'Informações Pessoais',
        'object'=> 'aluno',
        'min'=> '',
'maxlength'=>'',
        'max'=> '',
        'config' => '',
        'placeholder'=>"",
    ),
    array(
        'label' => 'Localidade',
        'id' => 'localidade',
        'name' => 'localidade',
        'type' => 'combobox',
        'size' =>'mb-3 col-md-3',
        'divisao' => 'Informações Pessoais',
        'object'=> 'aluno',
        'min'=> '',
'maxlength'=>'',
        'max'=> '',
        'config' => '',
        'placeholder'=>"",
    ),
    array(
        'label' => 'Código Postal',
        'id' => 'postal_code',
        'name' => 'codigo_postal_aluno',
        'type' => 'text',
        'size' => 'mb-3 col-md-3',
        'divisao' => 'Informações Pessoais',
        'object' => 'aluno',
        'min' => '',
        'maxlength' => '8',
        'max' => '',
        'config' => 'pattern="[0-9]{4}-[0-9]{3}"',
        'placeholder'=>"xxxx-xxx",
        
    ),
  
    array(
        'label' => 'Morada',
        'id' => 'address',
        'name' => 'morada_aluno',
        'type' => 'text',
        'size' => 'mb-3 col-md-3',
        'divisao' => 'Informações Pessoais',
        'object' => 'aluno',
        'min' => '',
        'maxlength' => '100',
        'max' => '',
        'config' => '',
        'placeholder'=>"Rua xxxxx, Nº xxx",
    ),

 

   

    array(
        'label' => 'Nome do Encarregado de Educação',
        'id' => 'encarregadoeducacao',
        'name' => 'encarregadoeducacao',
        'type' => 'combobox',
        'size' =>'mb-3 col-md-3',
        'divisao' => 'Encarregado de Educação',
        'object'=> 'aluno',
        'min'=> '',
        'maxlength'=>'',
        'max'=> '',
        'config' => '',
        'placeholder'=>"",
    ),
 

    
   
    array(
        'label' => 'Escola',
        'id' => 'escola',
        'name' => 'escola',
        'type' => 'combobox',
        'ajax' => array(
                        'file' =>'escola_turmas',
                        'div' => 'escola_turmas'
                        ),
        'size' => 'mb-3 col-md-3',
        'divisao' => 'Informações Escolares',
        'object' => 'aluno',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => 'onchange="id_selected("escola")"',
        'placeholder'=>"",
    ),
  
    array(
        'label' => 'Turma',
        'id' => 'turma',
        'name' => 'turma',
        'type' => 'combobox',
        'size' => 'mb-3 col-md-3',
        'divisao' => 'Informações Escolares',
        'object' => 'aluno',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => '',
        'placeholder'=>"",
    ),
    
    //colaboradores
    array(
        'label' => 'Nome do Colaborador',
        'id' => 'name',
        'name' => 'colaborador',
        'type' => 'text',
        'divisao' => 'Informações Pessoais',
        'size' =>'mb-3 col-md-3',
        'object'=> 'colaborador',
        'min'=> '',
'maxlength'=>'',
        'max'=> '',
        'config' => '',
        'placeholder'=>"",
    ),
    
    array(
        'label' => 'Número de cartão de cidadão ',
        'id' => 'cc',
        'name' => 'cc',
        'type' => 'number',
        'size' =>'mb-3 col-md-3',
        'divisao' => 'Informações Pessoais',
        'object'=> 'colaborador',
        'min'=> '',
        'maxlength'=>'',
        'max'=> '',
        'config' => '',
        'placeholder'=>"",
    ),
    array(
        'label' => 'Assunto ',
        'id' => 'cc',
        'name' => 'cc',
        'type' => 'text',
        'size' =>'mb-3 col-md-6',
        'divisao' => 'Enviar email',
        'object'=> 'email',
        'min'=> '',
        'maxlength'=>'',
        'max'=> '',
        'config' => '',
        'placeholder'=>"",
    ),
    array(
        'label' => 'Corpo do email ',
        'id' => 'cc',
        'name' => 'cc',
        'type' => 'text',
        'size' =>'mb-3 col-md-12',
        'divisao' => 'Enviar email',
        'object'=> 'email',
        'min'=> '',
        'maxlength'=>'',
        'max'=> '',
        'config' => '',
        'placeholder'=>"",
    ),


);