<?php
if(isset($tabela)){
    $id_unico = my_query("SELECT MAX(unico) FROM $tabela");
    $id_unico = $id_unico[0]['MAX(unico)'] + 1;
}else{
$id_unico = 0;
}
if(isset($id_aluno)){

}else{
    $id_aluno = 0;
}


$GLOBALS['campos'] = array(
    array(
        
        'id' => 'foto',
        'name' => 'foto_aluno',
        'type' => 'hidden',
        'divisao' => 'Informações Pessoais',
        'object'=> 'aluno',
        'min'=> '',
        'maxlength'=>'',
        'max'=> '',
        'config' => '',
        
    ),
    array(
        'label' => 'Nome do Aluno',
        'id' => 'name',
        'name' => 'aluno',
        'type' => 'text',
        'divisao' => 'Informações Pessoais',
        'size' =>'mb-3 col-md-3',
        'object'=> 'aluno',
        'min'=> '',
        'maxlength'=>'',
        'max'=> '',
        'config' => '',
        'placeholder'=>"Nome completo do aluno",
    ),
    
   array(
        'label' => 'Número do cartão de cidadão ',
        'id' => 'cc',
        'name' => 'cc_aluno',
        'type' => 'number',
        'size' =>'mb-3 col-md-3',
        'divisao' => 'Informações Pessoais',
        'object'=> 'aluno',
        'min'=> '',
        'maxlength'=>'9',
        'max'=> '',
        'config' => '',
        'placeholder'=>"Número do Cartão de Cidadão",
    ),
    array(
        'label' => 'Número de contribuinte (NIF)',
        'id' => 'nif',
        'name' => 'nif_aluno',
        'type' => 'text',
        'size' =>'mb-3 col-md-3',
        'divisao' => 'Informações Pessoais',
        'object'=> 'aluno',
        'min'=> '',
        'maxlength'=>'9',
        'max'=> '',
        'config' => '',
        'placeholder'=>"Número de Contribuinte",
    ),
    array(
        'label' => 'Número de Segurança Social',
        'id' => 'sc',
        'name' => 'sc_aluno',
        'type' => 'number',
        'size' =>'mb-3 col-md-3',
        'divisao' => 'Informações Pessoais',
        'object'=> 'aluno',
        'min'=> '',
        'maxlength'=>'',
        'max'=> '',
        'config' => '',
        'placeholder'=>"Numero da segurança social",
    ),
    array(
        'label' => 'Número de Telefone',
        'id' => 'telefone',
        'name' => 'telefone_aluno',
        'type' => 'number',
        'size' =>'mb-3 col-md-3',
        'divisao' => 'Informações Pessoais',
        'object'=> 'aluno',
        'min'=> '',
      
        'max'=> '',
        'config' => 'pattern="[0-9]{9}"',
        'placeholder'=>"123 456 789",
    ),
    array(
        'label' => 'Email do Aluno',
        'id' => 'email',
        'name' => 'email_aluno',
        'type' => 'email',
        'size' => 'mb-3 col-md-3',
        'divisao' => 'Informações Pessoais',
        'object' => 'aluno',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => '',
        'placeholder'=>"aluno@gmail.com",
    ),

    array(
        'label' => 'Data de Nascimento ',
        'id' => 'date',
        'name' => 'data_nascimento_aluno',
        'type' => 'date',
        'size' =>'mb-3 col-md-3',
        'divisao' => 'Informações Pessoais',
        'object'=> 'aluno',
        'min'=> date('Y-m-d', strtotime('-19 years')),
        'maxlength'=>'',
        'max'=> date('Y-m-d', strtotime('-6 years')),
        'config' => '',
        'placeholder'=>"",
    ),

    array(
        'label' => 'Género',
        'id' => 'genero',
        'name' => 'genero',
        'type' => 'combobox',
        'size' =>'mb-3 col-md-3',
        'divisao' => 'Informações Pessoais',
        'object'=> 'aluno',
        'min'=> '',
'maxlength'=>'',
        'max'=> '',
        'config' => '',
        'placeholder'=>"",
    ),
    array(
        'label' => 'Localidade',
        'id' => 'localidade',
        'name' => 'localidade',
        'type' => 'combobox',
        'size' =>'mb-3 col-md-3',
        'divisao' => 'Informações Pessoais',
        'object'=> 'aluno',
        'min'=> '',
'maxlength'=>'',
        'max'=> '',
        'config' => '',
        'placeholder'=>"",
    ),
    array(
        'label' => 'Código Postal',
        'id' => 'postal_code',
        'name' => 'codigo_postal_aluno',
        'type' => 'text',
        'size' => 'mb-3 col-md-3',
        'divisao' => 'Informações Pessoais',
        'object' => 'aluno',
        'min' => '',
        'maxlength' => '8',
        'max' => '',
        'config' => 'pattern="[0-9]{4}-[0-9]{3}"',
        'placeholder'=>"xxxx-xxx",
        
    ),
  
    array(
        'label' => 'Morada',
        'id' => 'address',
        'name' => 'morada_aluno',
        'type' => 'text',
        'size' => 'mb-3 col-md-3',
        'divisao' => 'Informações Pessoais',
        'object' => 'aluno',
        'min' => '',
        'maxlength' => '100',
        'max' => '',
        'config' => '',
        'placeholder'=>"Rua xxxxx, Nº xxx",
    ),

 

   

    array(
        'label' => 'Nome do Encarregado de Educação',
        'id' => 'encarregadoeducacao',
        'name' => 'encarregadoeducacao',
        'type' => 'combobox',
        'size' =>'mb-3 col-md-3',
        'divisao' => 'Encarregado de Educação',
        'object'=> 'aluno',
        'min'=> '',
        'maxlength'=>'',
        'max'=> '',
        'config' => '',
        'placeholder'=>"",
    ),
 

    
   
    array(
        'label' => 'Escola',
        'id' => 'escola',
        'name' => 'escola',
        'type' => 'combobox',
        'ajax' => array(
                        'file' =>'escola_turmas',
                        'div' => 'escola_turmas'
                        ),
        'size' => 'mb-3 col-md-3',
        'divisao' => 'Informações Escolares',
        'object' => 'aluno',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => 'onchange="id_selected("escola")"',
        'placeholder'=>"",
    ),
  
    array(
        'label' => 'Turma',
        'id' => 'turma',
        'name' => 'turma',
        'type' => 'combobox',
        'size' => 'mb-3 col-md-3',
        'divisao' => 'Informações Escolares',
        'object' => 'aluno',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => '',
        'placeholder'=>"",
    ),
    
    //colaboradores
    array(
        'label' => 'Nome do Colaborador',
        'id' => 'name',
        'name' => 'colaborador',
        'type' => 'text',
        'divisao' => 'Informações Pessoais',
        'size' =>'mb-3 col-md-3',
        'object'=> 'colaborador',
        'min'=> '',
'maxlength'=>'',
        'max'=> '',
        'config' => '',
        'placeholder'=>"",
    ),
    
    array(
        'label' => 'Número de cartão de cidadão ',
        'id' => 'cc',
        'name' => 'cc',
        'type' => 'number',
        'size' =>'mb-3 col-md-3',
        'divisao' => 'Informações Pessoais',
        'object'=> 'colaborador',
        'min'=> '',
        'maxlength'=>'',
        'max'=> '',
        'config' => '',
        'placeholder'=>"",
    ),
  
    array(
        'label' => 'Assunto ',
        'id' => 'cc',
        'name' => 'cc',
        'type' => 'text',
        'size' =>'mb-3 col-md-6',
        'divisao' => 'Enviar email',
        'object'=> 'email',
        'min'=> '',
        'maxlength'=>'',
        'max'=> '',
        'config' => '',
        'placeholder'=>"",
    ),
    array(
        'label' => 'Corpo do email ',
        'id' => 'cc',
        'name' => 'cc',
        'type' => 'text',
        'size' =>'mb-3 col-md-12',
        'divisao' => 'Enviar email',
        'object'=> 'email',
        'min'=> '',
        'maxlength'=>'',
        'max'=> '',
        'config' => '',
        'placeholder'=>"",
    ),


    //notas 
    array(
        'label' => 'Título',
        'id' => 'titulo',
        'name' => 'titulo',
        'type' => 'text',
        'size' =>'mb-3 col-md-10',
        'divisao' => 'Nota',
        'object'=> 'nota',
        'min'=> '',
        'maxlength'=>'',
        'max'=> '',
        'config' => '',
        'placeholder'=>"",
    ),
    array(
        'label' => 'Nota',
        'id' => 'nota',
        'name' => 'nota',
        'type' => 'textarea',
        'size' =>'mb-3 col-md-13',
        'divisao' => 'Nota',
        'object'=> 'nota',
        'min'=> '',
        'maxlength'=>'',
        'max'=> '',
        'config' => '',
        'placeholder'=>"",
    ),
    array(
        'label' => 'Destinatários',
        'id' => 'cargo',
        'name' => 'destinatario',
        'type' => 'combobox',
        'size' =>'mb-3 col-md-10',
        'divisao' => 'Nota',
        'object'=> 'nota',
        'min'=> '',
        'maxlength'=>'',
        'max'=> '',
        'config' => '',
        'placeholder'=>"",
    ),
    array(
        'label' => '',
        'id' => 'colaborador',
        'name' => 'colaborador',
        'type' => 'hidden',
        'size' =>'',
        'divisao' => 'Nota',
        'object'=> 'nota',
        'min'=> '',
        'maxlength'=>'',
        'max'=> '',
       
        'config' => ' value = "'.(isset($_SESSION['userID']) ? $_SESSION['userID'] : '').'"',

        'defenido'=>1,
        'placeholder'=>"",
    ),
    array(
        'label' => 'Operation',
        'id' => 'operacao',
        'name' => 'operacao',
        'type' => 'combobox',
        'size' =>'mb-3 col-md-3',
        'divisao' => '',
        'object'=> 'permissao',
        'min'=> '',
        'maxlength'=>'',
        'max'=> '',
        'config' => '',
        'placeholder'=>"",
    ),

    array(
        'label' => 'Cargo',
        'id' => 'cargo',
        'name' => 'cargo',
        'type' => 'combobox',
        'size' =>'mb-3 col-md-10',
        'divisao' => 'Permissao',
        'object'=> 'permissao',
        'min'=> '',
        'maxlength'=>'',
        'max'=> '',
        'config' => '',
        'placeholder'=>"",
    ),
    array(
        'label' => 'Nome',
        'id' => 'pessoa',
        'name' => 'pessoa',
        'type' => 'text',
        'size' =>'mb-3 col-md-10',
        'divisao' => 'pessoa',
        'object'=> 'pessoa',
        'min'=> '',
        'maxlength'=>'',
        'max'=> '',
        'config' => '',
        'placeholder'=>"",
    ),
    array(
        'label' => 'Número de Telefone',
        'id' => 'telefone',
        'name' => 'telefone_pessoa',
        'type' => 'number',
        'size' =>'mb-3 col-md-5',
        'divisao' => '',
        'object'=> 'pessoa',
        'min'=> '',
        'max'=> '',
        'config' => 'pattern="[0-9]{9}"',
        'placeholder'=>"123 456 789",
    ),

    array(
        'label' => 'Relação',
        'id' => 'relacao',
        'name' => 'relacao',
        'type' => 'combobox',
        'size' =>'mb-3 col-md-5',
        'divisao' => '',
        'object'=> 'pessoa',
        'min'=> '',
        'maxlength'=>'',
        'max'=> '',
        'config' => '',
        'placeholder'=>"",
    ),
    array(
        'label' => '',
        'id' => 'aluno',
        'name' => 'aluno',
        'type' => 'hidden',
        'size' =>'',
        'divisao' => '',
        'object'=> 'pessoa',
        'min'=> '',
        'maxlength'=>'',
        'max'=> '',
       
        'config' => ' value = "'.$id_aluno.'"',

        'defenido'=>1,
        'placeholder'=>"",
    ),
    array(
        'label' => '',
        'id' => 'aluno',
        'name' => 'unico',
        'type' => 'hidden',
        'size' => 'mb-3 col-md-3',
        'divisao' => '',
        'object' => 'aluno',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => ' value = "'.$id_unico.'"',
        'placeholder'=>"",
    ),
    
    array(
        'label' => '',
        'id' => 'ano',
        'name' => 'unico',
        'type' => 'hidden',
        'size' => 'mb-3 col-md-3',
        'divisao' => '',
        'object' => 'ano',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => ' value = "'.$id_unico.'"',
        'placeholder'=>"",
    ),
    
    array(
        'label' => '',
        'id' => 'cargo',
        'name' => 'unico',
        'type' => 'hidden',
        'size' => 'mb-3 col-md-3',
        'divisao' => '',
        'object' => 'cargo',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => ' value = "'.$id_unico.'"',
        'placeholder'=>"",
    ),
    
    array(
        'label' => '',
        'id' => 'ciclo',
        'name' => 'unico',
        'type' => 'hidden',
        'size' => 'mb-3 col-md-3',
        'divisao' => '',
        'object' => 'ciclo',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => ' value = "'.$id_unico.'"',
        'placeholder'=>"",
    ),
    
    array(
        'label' => '',
        'id' => 'colaborador',
        'name' => 'unico',
        'type' => 'hidden',
        'size' => 'mb-3 col-md-3',
        'divisao' => '',
        'object' => 'colaborador',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => ' value = "'.$id_unico.'"',
        'placeholder'=>"",
    ),
    
    array(
        'label' => '',
        'id' => 'conjunto',
        'name' => 'unico',
        'type' => 'hidden',
        'size' => 'mb-3 col-md-3',
        'divisao' => '',
        'object' => 'conjunto',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => ' value = "'.$id_unico.'"',
        'placeholder'=>"",
    ),
    array(
        'label' => '',
        'id' => 'nota',
        'name' => 'unico',
        'type' => 'hidden',
        'size' => 'mb-3 col-md-3',
        'divisao' => '',
        'object' => 'nota',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => ' value = "'.$id_unico.'"',
        'placeholder'=>"",
    ),
    
    array(
        'label' => '',
        'id' => 'disciplina',
        'name' => 'unico',
        'type' => 'hidden',
        'size' => 'mb-3 col-md-3',
        'divisao' => '',
        'object' => 'disciplina',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => ' value = "'.$id_unico.'"',
        'placeholder'=>"",
    ),
    
    array(
        'label' => '',
        'id' => 'encarregadoeducacao',
        'name' => 'unico',
        'type' => 'hidden',
        'size' => 'mb-3 col-md-3',
        'divisao' => '',
        'object' => 'encarregadoeducacao',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => ' value = "'.$id_unico.'"',
        'placeholder'=>"",
    ),
    
    array(
        'label' => '',
        'id' => 'escola',
        'name' => 'unico',
        'type' => 'hidden',
        'size' => 'mb-3 col-md-3',
        'divisao' => '',
        'object' => 'escola',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => ' value = "'.$id_unico.'"',
        'placeholder'=>"",
    ),
    
    array(
        'label' => '',
        'id' => 'especialidade',
        'name' => 'unico',
        'type' => 'hidden',
        'size' => 'mb-3 col-md-3',
        'divisao' => '',
        'object' => 'especialidade',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => ' value = "'.$id_unico.'"',
        'placeholder'=>"",
    ),
    
    array(
        'label' => '',
        'id' => 'evento',
        'name' => 'unico',
        'type' => 'hidden',
        'size' => 'mb-3 col-md-3',
        'divisao' => '',
        'object' => 'evento',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => ' value = "'.$id_unico.'"',
        'placeholder'=>"",
    ),
    
    array(
        'label' => '',
        'id' => 'formacao',
        'name' => 'unico',
        'type' => 'hidden',
        'size' => 'mb-3 col-md-3',
        'divisao' => '',
        'object' => 'formacao',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => ' value = "'.$id_unico.'"',
        'placeholder'=>"",
    ),
    
    array(
        'label' => '',
        'id' => 'genero',
        'name' => 'unico',
        'type' => 'hidden',
        'size' => 'mb-3 col-md-3',
        'divisao' => '',
        'object' => 'genero',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => ' value = "'.$id_unico.'"',
        'placeholder'=>"",
    ),
    
    array(
        'label' => '',
        'id' => 'localidade',
        'name' => 'unico',
        'type' => 'hidden',
        'size' => 'mb-3 col-md-3',
        'divisao' => '',
        'object' => 'localidade',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => ' value = "'.$id_unico.'"',
        'placeholder'=>"",
    ),
    
 
    
    array(
        'label' => '',
        'id' => 'nivel',
        'name' => 'unico',
        'type' => 'hidden',
        'size' => 'mb-3 col-md-3',
        'divisao' => '',
        'object' => 'nivel',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => ' value = "'.$id_unico.'"',
        'placeholder'=>"",
    ),
    
    array(
        'label' => '',
        'id' => 'nota',
        'name' => 'unico',
        'type' => 'hidden',
        'size' => 'mb-3 col-md-3',
        'divisao' => '',
        'object' => 'nota',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => ' value = "'.$id_unico.'"',
        'placeholder'=>"",
    ),
    
    array(
        'label' => '',
        'id' => 'operacao',
        'name' => 'unico',
        'type' => 'hidden',
        'size' => 'mb-3 col-md-3',
        'divisao' => '',
        'object' => 'operacao',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => ' value = "'.$id_unico.'"',
        'placeholder'=>"",
    ),
    
    array(
        'label' => '',
        'id' => 'permissao',
        'name' => 'unico',
        'type' => 'hidden',
        'size' => 'mb-3 col-md-3',
        'divisao' => '',
        'object' => 'permissao',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => ' value = "'.$id_unico.'"',
        'placeholder'=>"",
    ),
    
    array(
        'label' => '',
        'id' => 'pessoa',
        'name' => 'unico',
        'type' => 'hidden',
        'size' => 'mb-3 col-md-3',
        'divisao' => '',
        'object' => 'pessoa',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => ' value = "'.$id_unico.'"',
        'placeholder'=>"",
    ),
    
    array(
        'label' => '',
        'id' => 'relacao',
        'name' => 'unico',
        'type' => 'hidden',
        'size' => 'mb-3 col-md-3',
        'divisao' => '',
        'object' => 'relacao',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => ' value = "'.$id_unico.'"',
        'placeholder'=>"",
    ),
    
    array(
        'label' => '',
        'id' => 'servico',
        'name' => 'unico',
        'type' => 'hidden',
        'size' => 'mb-3 col-md-3',
        'divisao' => '',
        'object' => 'servico',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => ' value = "'.$id_unico.'"',
        'placeholder'=>"",
    ),
    
   
    
    array(
        'label' => '',
        'id' => 'statu',
        'name' => 'unico',
        'type' => 'hidden',
        'size' => 'mb-3 col-md-3',
        'divisao' => '',
        'object' => 'statu',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => ' value = "'.$id_unico.'"',
        'placeholder'=>"",
    ),
    
    array(
        'label' => '',
        'id' => 'transporte',
        'name' => 'unico',
        'type' => 'hidden',
        'size' => 'mb-3 col-md-3',
        'divisao' => '',
        'object' => 'transporte',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => ' value = "'.$id_unico.'"',
        'placeholder'=>"",
    ),
    
    array(
        'label' => '',
        'id' => 'turma',
        'name' => 'unico',
        'type' => 'hidden',
        'size' => 'mb-3 col-md-3',
        'divisao' => '',
        'object' => 'turma',
        'min' => '',
        'maxlength' => '',
        'max' => '',
        'config' => ' value = "'.$id_unico.'"',
        'placeholder'=>"",
    ),
    
);